[package]
name = "tinker"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = { version = "0.35", features = ["transparent"] }
tao = { version = "0.25", features = ["rwh_05"] }
raw-window-handle = "0.5.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = "0.6.20"
rumqttc = "0.22.0"
tokio = { version = "1.35.1", features = ["full"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
clap = { version = "4.4.12", features = ["derive"] }
anyhow = "1.0.79"
chrono = "0.4"
dotenv = "0.15"
url = "2.5.0"
thiserror = "1.0"
urlencoding = "2.1.3"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
